[package]
name = "memory-offset-match-test"
version = "0.1.0"
authors = ["Eike Siewertsen <eike@technocreatives.com>"]
edition = "2018"
publish = false

[dependencies]
memory-offset-match = { path = "../memory-offset-match" }
