[package]
name = "memory-offset-match-derive"
version = "0.1.0"
authors = ["Eike Siewertsen <eike@technocreatives.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
memory-offset-match-core = { path = "../memory-offset-match-core" }
proc-macro2 = "0.4.30"
